"use strict";

/* Cada acorde contém as notas que podem ser distribuídas entre os músicos. */
const CHORDS={C:["C4","E4","G4"],Dm:["D4","F4","A4"],Em:["E4","G4","B4"],F:["F4","A4","C5"],G:["G4","B4","D5"],Am:["A4","C5","E5"],"B°":["B4","D5","F5"]};
const STORAGE_KEY="scoreBuzzer.musicianScores.v1";
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
let selectedChord="C",selectedSlot=0,timers=[];
let state=createScore();

function createScore(){return{id:crypto.randomUUID?.()||String(Date.now()),name:"Nova partitura",musicians:[createMusician(1),createMusician(2)],slots:Array.from({length:16},()=>null),createdAt:new Date().toISOString()}}
function createMusician(number){return{id:`musico-${number}`,name:`Músico ${number}`}}
function notify(text){const t=$("#toastMessage");t.textContent=text;t.classList.add("show");clearTimeout(t.timer);t.timer=setTimeout(()=>t.classList.remove("show"),2500)}
function escapeHtml(value){const d=document.createElement("div");d.textContent=String(value);return d.innerHTML}
function assignmentFor(chord,index,musician){return{musicianId:musician.id,enabled:true,note:CHORDS[chord][index%CHORDS[chord].length]}}
function createEvent(chord){return{chord,duration:1,assignments:state.musicians.map((m,i)=>assignmentFor(chord,i,m))}}
function findAssignment(event,musicianId){return event?.assignments.find(a=>a.musicianId===musicianId)}

function renderPalette(){const root=$("#chordPalette");root.innerHTML="";Object.keys(CHORDS).forEach(chord=>{const b=document.createElement("button");b.type="button";b.className=`chord-button ${selectedChord===chord?"selected":""}`;b.textContent=chord;b.onclick=()=>{selectedChord=chord;$("#selectedChordLabel").textContent=chord;renderPalette()};root.appendChild(b)})}

function setSlot(index,value){selectedSlot=index;state.slots[index]=value;renderAll()}
function renderStaff(){const root=$("#staff");root.style.setProperty("--slots",state.slots.length);root.innerHTML="";state.slots.forEach((event,index)=>{const b=document.createElement("button");b.type="button";b.className=`staff-slot ${index%4===0?"measure-start":""} ${index===selectedSlot?"selected":""}`;const notes=event?event.assignments.filter(a=>a.enabled).map(a=>a.note).join(" · "):"";b.innerHTML=`<span class="slot-number">${Math.floor(index/4)+1}.${index%4+1}</span>${event?`<span class="chord-mark">${escapeHtml(event.chord)}</span><span class="slot-notes">${escapeHtml(notes)}<br>× ${event.duration}</span>`:""}`;b.onclick=()=>{selectedSlot=index;if(!event)state.slots[index]=createEvent(selectedChord);renderAll()};b.oncontextmenu=e=>{e.preventDefault();setSlot(index,null)};root.appendChild(b)});const used=state.slots.filter(Boolean).length;$("#slotCounter").textContent=`${used} de ${state.slots.length} posições utilizadas`;$("#eventCount").textContent=used}

function renderMusicians(){const root=$("#musicianList");root.innerHTML="";state.musicians.forEach((m,index)=>{const row=document.createElement("div");row.className="musician-item";row.innerHTML=`<input class="form-control form-control-sm musician-name" value="${escapeHtml(m.name)}" aria-label="Nome do músico"><button class="btn btn-sm btn-outline-danger ms-2 remove" type="button" ${state.musicians.length===1?"disabled":""}>×</button>`;row.querySelector(".musician-name").oninput=e=>{m.name=e.target.value;renderAssignments();updateJson()};row.querySelector(".remove").onclick=()=>removeMusician(index);root.appendChild(row)});$("#musicianCount").textContent=state.musicians.length}

function renderAssignments(){const root=$("#musicianAssignments"),event=state.slots[selectedSlot];root.innerHTML="";$("#eventInfo").textContent=event?`Posição ${selectedSlot+1}: acorde ${event.chord}`:`Posição ${selectedSlot+1}: pausa`;$("#duration").disabled=!event;$("#duration").value=event?.duration??1;if(!event){root.innerHTML='<p class="text-secondary mb-0">Insira um acorde nesta posição para configurar os músicos.</p>';return}state.musicians.forEach((m,index)=>{let a=findAssignment(event,m.id);if(!a){a=assignmentFor(event.chord,index,m);event.assignments.push(a)}const col=document.createElement("div");col.className="col-md-6 col-xl-4";col.innerHTML=`<div class="assignment-card ${a.enabled?"":"disabled"}"><div class="d-flex justify-content-between align-items-center"><strong>${escapeHtml(m.name)}</strong><div class="form-check form-switch"><input class="form-check-input enabled" type="checkbox" ${a.enabled?"checked":""}></div></div><label class="form-label small mt-2 mb-1">Nota</label><select class="form-select form-select-sm note" ${a.enabled?"":"disabled"}>${CHORDS[event.chord].map(n=>`<option ${n===a.note?"selected":""}>${n}</option>`).join("")}</select></div>`;col.querySelector(".enabled").onchange=e=>{a.enabled=e.target.checked;renderAll()};col.querySelector(".note").onchange=e=>{a.note=e.target.value;renderAll()};root.appendChild(col)})}

function addMusician(){const number=state.musicians.length+1,m=createMusician(number);state.musicians.push(m);state.slots.forEach(event=>{if(event)event.assignments.push(assignmentFor(event.chord,event.assignments.length,m))});renderAll()}
function removeMusician(index){if(state.musicians.length===1)return;const [removed]=state.musicians.splice(index,1);state.slots.forEach(event=>{if(event)event.assignments=event.assignments.filter(a=>a.musicianId!==removed.id)});renderAll()}

/* Produz exatamente o modelo: { "nome": [ [["C4","C3"],1], ["pausa",1] ] }. */
function buildJson(){const name=$("#scoreName").value.trim()||"sem_nome";const events=state.slots.map(event=>{if(!event)return["pausa",1];const notes=state.musicians.map(m=>findAssignment(event,m.id)).filter(a=>a?.enabled).map(a=>a.note);return notes.length?[notes,Number(event.duration)]:["pausa",Number(event.duration)]});return{[name]:events}}
function updateJson(){$("#jsonPreview").textContent=JSON.stringify(buildJson(),null,2)}
function getSaved(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||"[]")}catch{return[]}}
function saveScore(){if(!state.slots.some(Boolean))return notify("Adicione ao menos um acorde.");state.name=$("#scoreName").value.trim()||"Nova partitura";const list=getSaved().filter(x=>x.id!==state.id);list.unshift(structuredClone(state));localStorage.setItem(STORAGE_KEY,JSON.stringify(list));renderLibrary();notify("Partitura salva.")}
function downloadJson(){const data=JSON.stringify(buildJson(),null,2),blob=new Blob([data],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`${($("#scoreName").value.trim()||"partitura").replace(/[^a-z0-9_-]+/gi,"_")}.json`;a.click();URL.revokeObjectURL(a.href)}

function renderLibrary(){const root=$("#savedScores"),list=getSaved();root.innerHTML=list.length?"":'<p class="text-secondary">Nenhuma partitura salva.</p>';list.forEach(score=>{const col=document.createElement("div");col.className="col-md-6 col-xl-4";col.innerHTML=`<article class="card score-card shadow-sm"><div class="card-body"><h3 class="h5">${escapeHtml(score.name)}</h3><p class="small text-secondary">${score.musicians.length} músico(s) · ${score.slots.filter(Boolean).length} evento(s)</p><div class="sequence-preview">${score.slots.map(e=>e?.chord||"pausa").join(" · ")}</div><div class="d-flex gap-2 mt-3"><button class="btn btn-sm btn-primary open">Abrir</button><button class="btn btn-sm btn-outline-danger delete">Excluir</button></div></div></article>`;col.querySelector(".open").onclick=()=>{state=structuredClone(score);selectedSlot=0;syncForm();renderAll();showScreen("editor")};col.querySelector(".delete").onclick=()=>{localStorage.setItem(STORAGE_KEY,JSON.stringify(getSaved().filter(x=>x.id!==score.id)));renderLibrary()};root.appendChild(col)})}
function showScreen(id){$$('.screen').forEach(s=>s.classList.toggle('active-screen',s.id===id));$$('.menu-item').forEach(i=>i.classList.toggle('active',i.dataset.screen===id));if(innerWidth<992)$("#sidebar").classList.remove("open");if(id==="library")renderLibrary()}
function syncForm(){$("#scoreName").value=state.name;$("#slotCount").value=state.slots.length}
function resizeSlots(){const count=Math.max(4,Math.min(128,Math.ceil((Number($("#slotCount").value)||16)/4)*4));state.slots=Array.from({length:count},(_,i)=>state.slots[i]??null);selectedSlot=Math.min(selectedSlot,count-1);$("#slotCount").value=count;renderAll()}
function preview(){const indexes=state.slots.map((e,i)=>e?i:null).filter(i=>i!==null);if(!indexes.length)return notify("A partitura está vazia.");timers.forEach(clearTimeout);timers=indexes.map((i,order)=>setTimeout(()=>{$$('.staff-slot').forEach(s=>s.classList.remove('playing'));$$('.staff-slot')[i]?.classList.add('playing')},order*500));timers.push(setTimeout(()=>$$('.staff-slot').forEach(s=>s.classList.remove('playing')),indexes.length*500))}
function renderAll(){renderStaff();renderMusicians();renderAssignments();updateJson()}

$("#menuButton").onclick=()=>{const open=$("#sidebar").classList.toggle("open");$("#menuButton").setAttribute("aria-expanded",String(open))};$$('.menu-item').forEach(b=>b.onclick=()=>showScreen(b.dataset.screen));$("#addMusicianButton").onclick=addMusician;$("#slotCount").onchange=resizeSlots;$("#scoreName").oninput=updateJson;$("#duration").onchange=e=>{const event=state.slots[selectedSlot];if(event){event.duration=Number(e.target.value);renderAll()}};$("#restButton").onclick=()=>setSlot(selectedSlot,null);$("#clearButton").onclick=()=>{state.slots.fill(null);renderAll()};$("#saveButton").onclick=saveScore;$("#downloadButton").onclick=downloadJson;$("#previewButton").onclick=preview;$("#newScoreButton").onclick=()=>{state=createScore();selectedSlot=0;syncForm();renderAll();showScreen("editor")};
renderPalette();syncForm();renderLibrary();renderAll();
